---
# Spring Framework PetClinic — single Spring MVC WAR on Tomcat
# Web UI at http://localhost:8081  (NodePort 30081)
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: microservices-demo
  labels:
    app: petclinic
    app-type: petclinic
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
      name: http
  selector:
    app: petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: microservices-demo
  labels:
    app: petclinic
    app-type: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
        app-type: petclinic
    spec:
      nodeSelector:
        node-role: workload
      initContainers:
        - name: download-otel-agent
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              wget -q -O /otel/opentelemetry-javaagent.jar \
                https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.10.0/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel
      containers:
        - name: petclinic
          image: springcommunity/spring-framework-petclinic:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: "petclinic"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_TRACES_EXPORTER
              value: "none"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: otel-agent
              mountPath: /otel
          startupProbe:
            httpGet:
              path: /owners/find
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 36
          readinessProbe:
            httpGet:
              path: /owners/find
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /owners/find
              port: 8080
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: otel-agent
          emptyDir: {}
