apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    # Make this the default StorageClass so PVCs created by Prometheus and
    # Akamas without an explicit storageClassName are satisfied automatically.
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer   # provision EBS in the same AZ as the pod
reclaimPolicy: Retain                     # keep data if PVC is deleted accidentally
parameters:
  type: gp3
  encrypted: "true"
