# ServiceMonitors for Prometheus scraping
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: locust-monitor
  namespace: microservices-demo
  labels:
    app: ak-loadgenerator
spec:
  selector:
    matchLabels:
      app: ak-loadgenerator
  endpoints:
    - port: metrics
      interval: 15s
