apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: adservice
  namespace: microservices-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adservice
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: server
      target:
        type: Utilization
        averageUtilization: 80
