# This scenario emulates a bimodal workload of a day of 3 hours:
#   - 4 hours (morning) 350 users
#   - 4 hours (afternoon) 300 users
#   - 1 hours (launch) 50 users
#   - 13 hours (night) 10 users
# Moreover, has been introduce two peaks every week at night, simulating some batch workloads
apiVersion: v1
kind: Namespace
metadata:
  name: hipster-shop
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-scenario
  namespace: microservices-demo
data:
  scenario.json: |
    [
      {
        "n_users": 20,
        "spawn_rate": 0.5,
        "duration": 112
      },
      {
        "n_users": 350,
        "spawn_rate": 0.5,
        "duration": 30,
        "days": [1,3,4,5,7]
      },
      {
        "n_users": 350,
        "spawn_rate": 0.5,
        "duration": 16,
        "days": [2,6]
      },
      {
        "n_users": 500,
        "spawn_rate": 10,
        "duration": 14,
        "days": [2,6]
      },
      {
        "n_users": 50,
        "spawn_rate": 5,
        "duration": 8
      },
      {
        "n_users": 300,
        "spawn_rate": 10,
        "duration": 30
      }
    ]
