apiVersion: v1
kind: Namespace
metadata:
  name: hipster-shop
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-scenario
  namespace: microservices-demo
data:
  scenario.json: |
    [
      {"n_users": 50, "spawn_rate": 100000000, "duration": 1},
      {"n_users": 700, "spawn_rate": 100000000, "duration": 30}
    ]                                                                                                                        
    