# Kubernetes manifests for [Application Name]
#
# This file should contain all Kubernetes resources needed to deploy the application:
# - Deployments for each microservice
# - Services (ClusterIP, NodePort as needed)
# - ConfigMaps and Secrets (if any)
# - ServiceAccounts (if needed)
#
# Guidelines:
# - Use nodeSelector: node-role: workload for application pods
# - Use nodeSelector: node-role: tools for databases/infrastructure (if separate)
# - Add resource requests/limits for all containers
# - Add readiness, liveness, and startup probes
# - For JVM services, add OTel Java agent via init container (see online-boutique/adservice example)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
  namespace: microservices-demo
spec:
  selector:
    matchLabels:
      app: example-service
      app-type: [app-name]  # Important: identifies which app is deployed
  template:
    metadata:
      labels:
        app: example-service
        app-type: [app-name]
    spec:
      nodeSelector:
        node-role: workload
      containers:
        - name: server
          image: example/service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: microservices-demo
spec:
  type: ClusterIP
  selector:
    app: example-service
  ports:
    - port: 8080
      targetPort: 8080
